/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ilham Izzul
 */
public class JadwalDokter extends javax.swing.JFrame {

    /**
     * Creates new form JadwalDokter
     */
    public JadwalDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SDoc = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtusia = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtgol = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtkewar = new javax.swing.JTextField();
        txtpraktek = new javax.swing.JTextField();
        txtspesial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Pilih Dokter");

        SDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--->Pilih Salah Satu<---", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        SDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDocActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 33, -1, -1));

        txtnama.setEditable(false);
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 27, 212, 30));

        txtalamat.setEditable(false);
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 63, 212, 30));

        txtusia.setEditable(false);
        jPanel1.add(txtusia, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 99, 212, 30));

        txtjenis.setEditable(false);
        jPanel1.add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 135, 212, 30));

        txtgol.setEditable(false);
        jPanel1.add(txtgol, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 171, 212, 30));

        txtstatus.setEditable(false);
        jPanel1.add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 207, 212, 30));

        txtkewar.setEditable(false);
        jPanel1.add(txtkewar, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 243, 212, 30));

        txtpraktek.setEditable(false);
        jPanel1.add(txtpraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 279, 212, 30));

        txtspesial.setEditable(false);
        jPanel1.add(txtspesial, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 315, 212, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 69, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Usia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 105, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 141, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Gol. Darah");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 177, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 213, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setText("Kewarganegaraan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 249, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("Waktu Praktek");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 285, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Dokter Spesialis");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 321, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(SDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(124, 124, 124))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDocActionPerformed
                         
        // TODO add your handling code here: 
        if(SDoc.getSelectedItem().equals("DR. Farras Yassar")){ 
            txtnama.setText("DR. Farras Yassar ");
            txtalamat.setText("Jl. Surabaya 16, Malang");
            txtusia.setText("20 Tahun");
            txtjenis.setText("Laki-Laki");
            txtgol.setText("A"); 
            txtstatus.setText("Belum Menikah ");
            txtkewar.setText("Indonesia");
            txtspesial.setText("Dokter Umum");
            txtpraktek.setText(" Pagi (07.00-15.00)"); 
        }
        else 
        if(SDoc.getSelectedItem().equals("DR. Anisa Putri")){ 
            txtnama.setText("DR. Anisa Putri");
            txtalamat.setText("Jl. Veteran 3, Malang");
            txtusia.setText("20 Tahun");
            txtjenis.setText("Perempuan");
            txtgol.setText("O"); 
            txtstatus.setText("Belum Menikah");
            txtkewar.setText("Indonesia");
            txtspesial.setText("Dokter Gigi");
            txtpraktek.setText(" Sore (16.00-22.00)"); 
        }
        else 
        if(SDoc.getSelectedItem().equals("DR. Harun Fajar")){ 
            txtnama.setText("DR. Harun Fajar ");
            txtalamat.setText("Jl. Bandung 9, Malang");
            txtusia.setText("20 Tahun");
            txtjenis.setText("Laki-Laki");
            txtgol.setText("B");
            txtstatus.setText("Belum Menikah");
            txtkewar.setText("Indonesia");
            txtspesial.setText("Dokter Gizi");
            txtpraktek.setText(" Malam (22.00-06.00)"); 
        } 
          

    }//GEN-LAST:event_SDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtgol;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtkewar;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpraktek;
    private javax.swing.JTextField txtspesial;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtusia;
    // End of variables declaration//GEN-END:variables
}
